/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Zhuier (https://sketchfab.com/Zhuier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oiiaioooooiai-cat-30d27bf7fb224849b76e208a6eccdb36
Title: Oiiaioooooiai Cat
*/

import React, { useRef,Suspense,useState } from 'react'
import { useGLTF, useAnimations ,Preload,OrbitControls} from '@react-three/drei'
import { Canvas, useFrame } from "@react-three/fiber";
import CanvasLoader from "../Loader";
import * as random from "maath/random/dist/maath-random.esm";

const Cat = (props)=> {
  
  const cat = useGLTF('./Cat/scene.gltf')
  const ref=useRef()
  useFrame((state, delta) => {
    ref.current.rotation.y -= delta / 0.7;
    
  });
  return (
    <primitive ref={ref} object={cat.scene} scale={5.5} position-y={0} rotation-y={0}
     />
  )
}

 const CatCanvas = () => {
  
  
  
  return (
    <Canvas 
      shadows
      frameloop='demand'
      dpr={[1, 2]}
      gl={{ preserveDrawingBuffer: true }}
      camera={{
        fov: 55,
        near: 0.2,
        far: 300,
        position: [-4, 3, 6],
      }}
    >
      <Suspense fallback={<CanvasLoader />} >
        <OrbitControls
          autoRotate
          enableZoom={false}
          maxPolarAngle={Math.PI / 3}
          minPolarAngle={Math.PI / 3}
        />
        <ambientLight intensity={1.55} />
        <directionalLight position={[0, 0, 0.05]} />
        <Cat />

        <Preload all />
      </Suspense>
    </Canvas>
  );
};
export default CatCanvas;